### ISSUE TITLE
Message "DNA Center Python SDK is not installed. Execute 'pip install dnacentersdk'" with dnacentersdk already installed

### ISSUE THREAD

**Issue by petervillar** [cisco-en-programmability/dnacenter-ansible#121]
We have recently upgraded to 2.3.5.4 and I've  upgraded the cisco.dnac version and dnacentersdk version to the supported versions (6.7.5 and 2.6.0 respectively)

When I try to execute any playbook I get the following message:

```
Monday 16 October 2023  11:06:46 +0200 (0:00:00.603)       0:00:07.127 ********
The full traceback is:
NoneType: None
fatal: [dna.sr.se]: FAILED! => {
    "changed": false
}

MSG:

DNA Center Python SDK is not installed. Execute 'pip install dnacentersdk'

PLAY RECAP ***************************************************************************
```
dnacentersdk is installed

```
~/ansible_dnac$ pip list | grep dnacentersdk
dnacentersdk       2.6.0
```
But there seems to be missing a module in the v2.2.2.3-api (authentication_management):

```
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from dnacentersdk import api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xyzzy/ansible_dnac/venv/lib/python3.9/site-packages/dnacentersdk/__init__.py", line 30, in <module>
    from .api import DNACenterAPI
  File "/home/xyzzy/ansible_dnac/venv/lib/python3.9/site-packages/dnacentersdk/api/__init__.py", line 485, in <module>
    from .v2_3_3_0.authentication_management import \
ModuleNotFoundError: No module named 'dnacentersdk.api.v2_3_3_0.authentication_management'
```

This module is present in f.ex. v2.2.2.3 but not on v2.3.3.0:
```
~/ansible_dnac/venv/lib/python3.9$ ls site-packages/dnacentersdk/api/v2_2_2_3/authentication_management.py
site-packages/dnacentersdk/api/v2_2_2_3/authentication_management.py
~/ansible_dnac/venv/lib/python3.9$ ls site-packages/dnacentersdk/api/v2_3_3_0/authentication_management.py
ls: cannot access 'site-packages/dnacentersdk/api/v2_3_3_0/authentication_management.py': No such file or directory
```

**Comment by aaronhuff** [comment]
I used Ansible 2.10 and this worked, but I was having the exact same issue for Ansible 2.12 and 2.13. That doesn't make sense to me, why it would help with a missing module in the dnacentersdk package but maybe it helps!
