### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: invalid syntax (command_runner_run_command.py, line 79)

### ISSUE THREAD

**Issue by a083138** [cisco-en-programmability/dnacenter-ansible#19]
I am trying to use this Ansible module for the first time and getting the above error.  I get this no matter which of the sample  playbooks I test at https://github.com/cisco-en-programmability/dnacenter-ansible/tree/main/playbooks.  I am using the latest version of code.(3.1.6)

Below is the full error I see when I use this collection....

```
PLAY [Get Network Devices] *****************************************************
META: ran handlers
ERROR! Unexpected Exception, this is probably a bug: invalid syntax (command_runner_run_command.py, line 79)
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 127, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 241, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 248, in run
    action = action_loader.get(task.action, class_only=True)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 557, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 535, in _load_module_source
    module = imp.load_source(to_native(full_name), to_native(path), module_file)
  File "/var/lib/awx/.ansible/collections/ansible_collections/cisco/dnac/plugins/action/command_runner_run_command.py", line 79
    response = dnac.exec(
                       ^
SyntaxError: invalid syntax
```

**Comment by jbogarin** [comment]
@a083138 Have you tried with Python 3? Python 2.x is not supported.

**Comment by a083138** [comment]
> @a083138 Have you tried with Python 3? Python 2.x is not supported.

I can confirm I used Python 3 and it did resolve the issue and the modules are now all working ok.  Thanks for the advise!
