### ISSUE TITLE
Misspelled attribute when getting template details

### ISSUE THREAD

**Issue by ephracis** [cisco-en-programmability/dnacenter-ansible#209]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Ansible collection version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacenter-ansible/tree/main#compatibility-matrix) before opening an issue.

**Name of the module**
cisco.dnac.templates_details_info

**Describe the bug**

```
TASK [Get template details] ************************************************************************************************************************************************************************************************************************************
task path: /home/chre07/git/ansible-project-dcom-dnac/export.yml:6
The full traceback is:
Traceback (most recent call last):
  File "/home/chre07/.ansible/collections/ansible_collections/cisco/dnac/plugins/plugin_utils/dnac.py", line 209, in exec
    func = getattr(family, function)
AttributeError: 'ConfigurationTemplates' object has no attribute 'get_templates_details_v2'
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin (<ansible.plugins.callback.default.CallbackModule object at 0x7ff8b916a3a0>): Object of type AttributeError is not JSON serializable
Callback Exception: 
  File "/tmp/venv/lib64/python3.9/site-packages/ansible/executor/task_queue_manager.py", line 468, in send_callback
    method(*new_args, **kwargs)
   File "/tmp/venv/lib64/python3.9/site-packages/ansible/plugins/callback/default.py", line 67, in v2_runner_on_failed
    msg = "fatal: [%s]: FAILED! => %s" % (host_label, self._dump_results(result._result))
   File "/tmp/venv/lib64/python3.9/site-packages/ansible/plugins/callback/__init__.py", line 260, in _dump_results
    return json.dumps(OrderedDict(sorted(abridged_result.items(), key=to_text)),
   File "/usr/lib64/python3.9/json/__init__.py", line 234, in dumps
    return cls(
   File "/usr/lib64/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
   File "/usr/lib64/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
   File "/usr/lib64/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
   File "/usr/lib64/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
   File "/tmp/venv/lib64/python3.9/site-packages/ansible/module_utils/common/json.py", line 75, in default
    value = super(AnsibleJSONEncoder, self).default(o)
   File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
```

**Additional context**

If I change this line:
https://github.com/cisco-en-programmability/dnacenter-ansible/blob/1aa90c40adbb1263b4239f9f62324577ba982b04/plugins/action/templates_details_v2_info.py#L116C23-L116C47

From this:
function='get_templates_details_v2',

To this:
function='get_template_details_v2',

Then the module works.

**Comment by ephracis** [comment]
I would provide a pull request but I am not sure if you want to rename the action plugin and modules as well, as that would break compatibility.

**Comment by JosePabloOcampo1212** [comment]
Hello how are you?

I want to know what version of dnacentersdk you are using.?

**Comment by ephracis** [comment]
2.7.6

**Comment by ephracis** [comment]
Oh, I see they just released 2.7.7 with a rename of the function. So I guess it *is* supposed to be plural, and the bug was at the SDK then. :)
