### ISSUE TITLE
version 2.3.7.7 failed

### ISSUE THREAD

**Issue by JeanKean-art** [cisco-en-programmability/dnacenter-ansible#224]
Hi,

All the Playbooks are KO after upgrading DNACenter to 2.3.7.7.

For example : 

- name: Fetch devices
  cisco.dnac.network_device_info:
    dnac_host: "{{ dnac_host }}"
    dnac_username: "{{ dnac_username }}"
    dnac_password: "{{ dnac_password }}"
    dnac_verify: false
    dnac_port: 443
    offset: "{{ item }}"
    limit: "{{ block_size }}"
    family: ['Switches and Hubs']
  register: devices_block
  loop: "{{ offset_list }}"
  loop_control:
    label: "Offset: {{ item }}"

Debug : 

Callback Exception: 
  File "/usr/local/lib/python3.9/site-packages/ansible/executor/task_queue_manager.py", line 468, in send_callback
    method(*new_args, **kwargs)
   File "/runner/artifacts/205790/callback/awx_display.py", line 791, in v2_runner_item_on_failed
    with self.capture_event_data('runner_item_on_failed', **event_data):
   File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
   File "/runner/artifacts/205790/callback/awx_display.py", line 374, in capture_event_data
    event_context.dump_begin(sys.stdout)
   File "/runner/artifacts/205790/callback/awx_display.py", line 239, in dump_begin
    self.cache.set(":1:ev-{}".format(begin_dict['uuid']), begin_dict)
   File "/runner/artifacts/205790/callback/awx_display.py", line 114, in set
    partial_data = json.dumps(value, cls=AnsibleJSONEncoderLocal)
   File "/usr/lib64/python3.9/json/__init__.py", line 234, in dumps
    return cls(
   File "/usr/lib64/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
   File "/usr/lib64/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
   File "/runner/artifacts/205790/callback/awx_display.py", line 94, in default
    return super(AnsibleJSONEncoderLocal, self).default(o)
   File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
Callback Exception: 
  File "/usr/local/lib/python3.9/site-packages/ansible/executor/task_queue_manager.py", line 468, in send_callback
    method(*new_args, **kwargs)
   File "/runner/artifacts/205790/callback/awx_display.py", line 791, in v2_runner_item_on_failed
    with self.capture_event_data('runner_item_on_failed', **event_data):
   File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
   File "/runner/artifacts/205790/callback/awx_display.py", line 374, in capture_event_data
    event_context.dump_begin(sys.stdout)
   File "/runner/artifacts/205790/callback/awx_display.py", line 239, in dump_begin
    self.cache.set(":1:ev-{}".format(begin_dict['uuid']), begin_dict)
   File "/runner/artifacts/205790/callback/awx_display.py", line 114, in set
    partial_data = json.dumps(value, cls=AnsibleJSONEncoderLocal)
   File "/usr/lib64/python3.9/json/__init__.py", line 234, in dumps
    return cls(
   File "/usr/lib64/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
   File "/usr/lib64/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
   File "/runner/artifacts/205790/callback/awx_display.py", line 94, in default
    return super(AnsibleJSONEncoderLocal, self).default(o)
   File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

**Comment by JosePabloOcampo1212** [comment]
You could check the playbooks network_device_info . before reviewing and testing. You should update the library to the most recent version and send me screenshots of the errors if they appear.

![Captura de pantalla 2025-01-06 a las 1 38 01 p  m](https://github.com/user-attachments/assets/d1891c19-94d3-49fa-9afe-928142e7cb7a)

This is because it is working for me.

**Comment by JeanKean-art** [comment]
Hi @JosePabloOcampo1212, I got the same issue with this new version: 

TASK [fetch_cisco_dnac : TEST Get Device Interface] ****************************
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin
(<ansible.plugins.callback.awx_display.CallbackModule object at
0x7fefaaa6ed30>): **Object of type AttributeError is not JSON serializable**


- name: TEST Get Device Interface
  cisco.dnac.interface_network_device_info:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: false
    dnac_port: 443
    #dnac_version: 2.3.7.6
    deviceId: "06d9df5d-37c8-4c37-a8b0-976d599ae92e"
  register: test
  
  
  BUT this task is working : 
  
  - name: Get the total number of devices
  cisco.dnac.network_device_count_info:
    dnac_host: "{{ dnac_host }}"
    dnac_username: "{{ dnac_username }}"
    dnac_password: "{{ dnac_password }}"
    dnac_verify: false
    dnac_port: 443
  register: total_devices_response

**Comment by JosePabloOcampo1212** [comment]
You could try changing this deviceId: "06d9df5d-37c8-4c37-a8b0-976d599ae92e" to this deviceId: 06d9df5d-37c8-4c37-a8b0-976d599ae92e

**Comment by JeanKean-art** [comment]
I got the same issue : 

[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin
(<ansible.plugins.callback.awx_display.CallbackModule object at
0x7f5807306d30>): Object of type AttributeError is not JSON serializable

**Comment by JeanKean-art** [comment]
I got a debug error message : 

  "test": "{'failed': True, 'msg': AttributeError(\"'Devices' object has no attribute 'get_interface_info_by_id_v1'\"), 'exception': 'Traceback (most recent call last):\\n  File \"/usr/share/ansible/collections/ansible_collections/cisco/dnac/plugins/plugin_utils/dnac.py\", line 209, in exec\\n    func = getattr(family, function)\\nAttributeError: \\'Devices\\' object has no attribute \\'get_interface_info_by_id_v1\\'\\n', 'changed': False}",

**Comment by JosePabloOcampo1212** [comment]
could you update dnacentersdk to version 2.8.2
